on: push
#on:
#  push:
#    branches:    
#      - master
#    paths:
#      - 'test/node/**'
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
        
    - name: Install Aws | Kubectl
      run: ./.github/scripts/aws-cli.sh
      shell: bash

    - name: Install Eksctl
      run: ./.github/scripts/eksctl.sh
      shell: bash

    - name: Connect to Aws / Configure Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_NODE }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY_NODE }}
        aws-region: us-east-1  

    - name: Run build script
      run: ./.github/scripts/deployment.sh
      shell: bash

      env:
        files: ${{ steps.changed-files.outputs.all_changed_files }}